### find all
GET http://localhost:3000/api/lineaCarga/

### add 
# @name lineaCargaCreated
POST http://localhost:3000/api/lineaCarga/
Content-Type: application/json

{
    "cantidadVagon": 10,
    "idCarga": 1,
    "idViaje": 2
}

###ID
@id = {{lineaCargaCreated.response.body.data.id}}

### find one
GET http://localhost:3000/api/lineaCarga/{{id}}

### update 
PUT http://localhost:3000/api/lineaCarga/{{id}}
Content-Type: application/json

{
    "cantidadVagon": 10,
    "idCarga": 1,
    "idViaje": 2
}

### delete
DELETE http://localhost:3000/api/lineaCarga/{{id}}