### Obtener todas las observacion
GET http://localhost:3000/api/observacion
Content-Type: application/json


### Obtener una observación por ID
GET http://localhost:3000/api/observacion/1
Content-Type: application/json


### Crear una nueva observación
POST http://localhost:3000/api/observacion
Content-Type: application/json

{
  "observaciones": "Demora en el tren",
  "fecha": "2025-08-03T10:00:00.000Z",
  "idCategoria": 1,
  "idViaje": 8
}


### Actualizar una observación existente
PUT http://localhost:3000/api/observacion/1
Content-Type: application/json

{
  "observaciones": "Tren cancelado sin aviso",
  "fecha": "2025-08-03T14:30:00.000Z",
  "idCategoria": 1,
  "idViaje": 5
}


### Eliminar una observación
DELETE http://localhost:3000/api/observacion/1
