### GET ALL
GET http://localhost:3000/api/tren/

### POST
# @name trenCreated
POST http://localhost:3000/api/tren/
Content-Type: application/json

{
  "color": "Naranja",
  "modelo": "Ben 10"
}

### ID
@id = {{trenCreated.response.body.data.id}}

### FIND ONE
GET http://localhost:3000/api/tren/{{id}}

### PUT
PUT http://localhost:3000/api/tren/{{id}}
Content-Type: application/json

{
  "color": "Rosa",
  "modelo": "Peppa Pig"
}

### DELETE
@idToDelete = {{trenCreated.response.body.data.id}}
DELETE http://localhost:3000/api/tren/{{id}}