### GET ALL
GET http://localhost:3000/api/licencia/

### POST
# @name licenciaCreated
POST http://localhost:3000/api/licencia/
Content-Type: application/json

{
    "fechaVencimiento": "2024-12-31",
    "fechaHecho": "2023-10-01",
    "estado": "activo",
    "idConductor": 2
}

### ID
@id = {licenciaCreated.response.body.data.id}

### FIND ONE
GET http://localhost:3000/api/licencia/{{id}}

### PUT
PUT http://localhost:3000/api/licencia/3
Content-Type: application/json

{
    "fechaVencimiento": "2020-12-31"
}

### DELETE
@idToDelete = {licenciaCreated.response.body.data.id}
DELETE http://localhost:3000/api/licencia/5